# -*- coding: utf-8 -*-
"""Pandas 611.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wneNjpUa69bGd_6ksTyFC9lBFKs_Mzm

Mavzu:Mantiq va oddiy intellektual masalalar. Python yordamida mantiqiy masalalarni yechish, propositsion mantiq bilan ishlash, oddiy inference- engine yaratish.
"""

import pandas as pd

royhat={
    "Ism":[ "Zulayho" ,"Ali","Vali" ],
    "Familiya":["Qadamova","Aliyev","Valiyev"],
    "Yoshi":[29, 15,20],
    "Manzili":["Farg'ona shaxar","Qo'qon shaxar","Farg'ona shaxar"],
    "Jinsi":["ayol","erkak","erkak"]

}
baza=pd.DataFrame(royhat)
print(baza)

filtr=baza[baza['Yoshi']<=15]
print(filtr)

filtr=baza[baza["Manzili"]=="Farg'ona shaxar"]
print(filtr)

yildankeyin=baza["Yoshi"]+30
yildankeyin

titanik=pd.read_csv("/content/titanic.csv")
print(titanik)